templproject/templapp/urls.py
from django.urls import path
from templapp import views

# SET UP TEMPLATE TAGGING!!
# django will automatically look for app_name
# tells django to look into templapp and find the urls that match
app_name = "templapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("filter", views.filter_example, name="filter_example"),
]

templproject/templproject/urls.py
from django.contrib import admin
from django.urls import path, include
from templapp import views 

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("templapp/", include("templapp.urls")),
]

templproject/templapp/models.py
from django.db import models

# Create your models here.

templproject/templapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"templapp/index.html")

def filter_example(request):
    context_dict = {"text":"Hello World","number":100}
    return render(request,"templapp/filter.html",context_dict)

templproject/templates/templapp/base.html
<!DOCTYPE html>
<!--  this has to always be the first line -->

{% load static %}

<head>
    <meta charset="UTF-8">
    <!-- latest compiled and minified css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "templapp/css/base.css" %}>

    <!-- link to fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet"
    />
    <title></title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'templapp:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'templapp:filter_example' %}">Filters page</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        {% block body_block %}
        <!-- anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>

</body>

</html>

templproject/templates/templapp/filter.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% load custom_filters %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Page showing Django Template Filters</h1>
<br>
<h3>{{ text }}</h3>
<h3>{{ text | upper }}</h3>
<h3>{{ text | cut:'Hello' }}</h3>
<h3>{{ text | slice:3 }}</h3>
<br>
<h3>{{ number|add:"99" }}</h3>
{% endblock %}

templproject/templates/templapp/index.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Index Page with an example of template inheritance</h1>
<br>
<p>This is the index page with inheritance from the base.html template.</p>
<p><a href="{% url 'templapp:filter_example' %}">Go to the page with the example of custom filters</a></p>
{% endblock %}

templproject/templates/templapp/index_filter.html
<!DOCTYPE html>

{% extends "templapp/base.html" %}

{% load custom_filters %}

{% block body_block %}
<!-- anything inside this is specific of this individual html -->
<h1>Page showing Django Template Filters</h1>
<br>
<h3>{{ text }}</h3>
<h3>{{ text | upper }}</h3>
<h3>{{ text | cut:'Hello' }}</h3>
<h3>{{ text | slice:3 }}</h3>
<br>
<h3>{{ number|add:"99" }}</h3>
{% endblock %}